name: cibuildwheel

on:
  workflow_call:
    inputs:
      auto-archs:
        description: Build wheels for auto archs
        required: true
        type: boolean
      extral-archs:
        description: Build wheels for aarch64 armv7l ppc64le & s390x
        required: true
        type: boolean

jobs:
  build_wheels:
    name: Build ${{ matrix.build }}-${{ matrix.arch }} wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        build: [manylinux, musllinux]
        arch: [aarch64, ppc64le, s390x, armv7l, x86_64, i686]
        os: [ubuntu-24.04] # renovate: github-runner
        use_qemu: [true]
        include:
          - {os: windows-2019, arch: AMD64, build: win, use_qemu: false}
          - {os: windows-2019, arch: x86, build: win, use_qemu: false}
          - {os: windows-2022, arch: ARM64, build: win, use_qemu: false}
          - {os: macos-13, arch: x86_64, build: macos, use_qemu: false}
          - {os: macos-14, arch: arm64, build: macos, use_qemu: false}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        if: >
          github.event.inputs.extral-archs && matrix.use_qemu ||
          github.event.inputs.auto-archs && !matrix.use_qemu
        with:
          fetch-depth: 0

      - name: Set up msvc on Windows
        if: runner.os == 'Windows' && github.event.inputs.auto-archs && !matrix.use_qemu
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1
        with:
          arch: ${{ matrix.arch }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
        if: runner.os == 'Linux' && github.event.inputs.extral-archs && matrix.use_qemu

      - name: Build wheels
        if: >
          github.event.inputs.extral-archs && matrix.use_qemu ||
          github.event.inputs.auto-archs && !matrix.use_qemu
        uses: pypa/cibuildwheel@ee63bf16da6cddfb925f542f2c7b59ad50e93969 # v2.22.0
        env:
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_BUILD: '*${{ matrix.build }}*'

      - name: Upload wheels
        if: >
          github.event.inputs.extral-archs && matrix.use_qemu ||
          github.event.inputs.auto-archs && !matrix.use_qemu
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        with:
          name: cibw-${{ matrix.build }}-${{ matrix.arch }}-${{ matrix.os }}
          path: wheelhouse/*.whl
