name: cibuildwheel

on:
  workflow_call:
    inputs:
      auto:
        description: Build wheels for auto archs
        required: true
        type: boolean
      extra:
        description: Build wheels for aarch64 armv7l ppc64le & s390x
        required: true
        type: boolean

jobs:
  build_wheels:
    name: On ${{ matrix.os }}, with ${{ matrix.arch }}, build ${{ matrix.build }} wheels
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-24.04] # renovate: github-runner
        arch: [aarch64, ppc64le, s390x, armv7l, x86_64, i686]
        build: [manylinux, musllinux]
        qemu_arch: [aarch64 ppc64le s390x armv7l]
        include:
          - {os: windows-2019, arch: AMD64, build: win}
          - {os: windows-2019, arch: x86, build: win}
          - {os: windows-2022, arch: ARM64, build: win}
          - {os: macos-13, arch: x86_64, build: macos}
          - {os: macos-14, arch: arm64, build: macos}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        if: >
          inputs.auto && !contains(matrix.qemu_arch, matrix.arch) ||
          inputs.extra && contains(matrix.qemu_arch, matrix.arch)
        with:
          fetch-depth: 0

      - name: Set up msvc on Windows
        if: runner.os == 'Windows' && inputs.auto && !contains(matrix.qemu_arch, matrix.arch)
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1
        with:
          arch: ${{ matrix.arch }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
        if: runner.os == 'Linux' && inputs.extra && contains(matrix.qemu_arch, matrix.arch)

      - name: Build wheels
        if: >
          inputs.auto && !contains(matrix.qemu_arch, matrix.arch) ||
          inputs.extra && contains(matrix.qemu_arch, matrix.arch)
        uses: pypa/cibuildwheel@ee63bf16da6cddfb925f542f2c7b59ad50e93969 # v2.22.0
        env:
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_BUILD: '*${{ matrix.build }}*'

      - name: Upload wheels
        if: >
          inputs.auto && !contains(matrix.qemu_arch, matrix.arch) ||
          inputs.extra && contains(matrix.qemu_arch, matrix.arch)
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        with:
          name: cibw-${{ matrix.os }}-${{ matrix.build }}-${{ matrix.arch }}
          path: wheelhouse/*.whl
